project 'ReactiveCocoaBase.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveCocoaBase' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   pod 'ReactiveCocoa'
   pod 'AFNetworking'
  # Pods for ReactiveCocoaBase

  target 'ReactiveCocoaBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveCocoaBaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
